name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save 6e05a6b3-6a6c-48af-a552-0c412530660b
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
